codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        informational: true
      patch:
        default:
          informational: true

comment:
  layout: "condensed_header, diff, flags, files, condensed_footer"
  behavior: default
  require_changes: false
