[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Project details

[project]
name = "celadon-theme"
dynamic = ["version"]
description = "A ceramic-inspired IDE dark theme generator using Python and Jinja2"
readme = "README.md"
license = { file = "LICENSE.md" }
authors = [
    { name = "Alif Naufal", email = "alif898@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "pathspec>=1.1.1",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pyyaml>=6.0.3",
    "reportlab>=4.4.10",
    "svglib>=1.6.0",
    "lxml>=6.1.1",
    "markdown-it-py>=4.2.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.16.2",
    "ty>=0.0.69",
    "types-PyYAML>=6.0.12.20260724",
]

[project.urls]
Homepage = "https://github.com/alif898/celadon-theme"
Issues = "https://github.com/alif898/celadon-theme/issues"

[project.scripts]
celadon-theme = "celadon_theme.main:main"

# Tooling

[tool.hatch.version]
path = "config.json"
pattern = "\"version\":\\s*\"(?P<version>[^\"]+)\""

[tool.coverage.run]
source = ["src/celadon_theme"]
omit = [
    "*/tests/*",
    "*/test_*.py",
    "*/__init__.py",
    "src/celadon_theme/main.py",
    "src/celadon_theme/config/logging_config.py",
]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov=src/celadon_theme --cov-report=term-missing"
testpaths = ["tests"]

[tool.ty.src]
include = ["src", "tests"]

[tool.ty.rules]
unresolved-import = "ignore"

[tool.ruff]
src = ["src", "tests"]
include = ["src/**/*.py", "tests/**/*.py"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",
    "CPY001",
    "D",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]
